import type { Config } from "tailwindcss";

const config = {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        primary: "var(--qa-color-primary)",
        "primary-active": "var(--qa-color-primary-active)",
        "primary-disabled": "var(--qa-color-primary-disabled)",
        "canvas-dark": "var(--qa-color-canvas-dark)",
        "canvas-light": "var(--qa-color-canvas-light)",
        "surface-card": "var(--qa-color-surface-card)",
        "surface-elevated": "var(--qa-color-surface-elevated)",
        "surface-soft": "var(--qa-color-surface-soft)",
        "surface-strong": "var(--qa-color-surface-strong)",
        "hairline-light": "var(--qa-color-hairline-light)",
        "hairline-dark": "var(--qa-color-hairline-dark)",
        "border-strong": "var(--qa-color-border-strong)",
        ink: "var(--qa-color-ink)",
        body: "var(--qa-color-body)",
        "body-light": "var(--qa-color-body-on-light)",
        muted: "var(--qa-color-muted)",
        "muted-strong": "var(--qa-color-muted-strong)",
        "on-primary": "var(--qa-color-on-primary)",
        "on-dark": "var(--qa-color-on-dark)",
        info: "var(--qa-color-info)",
        success: "var(--qa-color-risk-reduce)",
        warning: "var(--qa-color-approval-expiring)",
        danger: "var(--qa-color-risk-increase)",
        "trading-up": "var(--qa-color-trading-up)",
        "trading-down": "var(--qa-color-trading-down)",
        "risk-increase": "var(--qa-color-risk-increase)",
        "risk-reduce": "var(--qa-color-risk-reduce)",
        "approval-expiring": "var(--qa-color-approval-expiring)",
      },
      borderRadius: {
        sm: "var(--qa-radius-sm)",
        md: "var(--qa-radius-md)",
        lg: "var(--qa-radius-lg)",
        xl: "var(--qa-radius-xl)",
        pill: "var(--qa-radius-pill)",
      },
      boxShadow: {
        card: "var(--qa-shadow-card)",
        modal: "var(--qa-shadow-modal)",
        focus: "var(--qa-shadow-focus)",
      },
      spacing: {
        xxs: "0.25rem",
        xs: "0.5rem",
        sm: "0.75rem",
        md: "1rem",
        lg: "1.5rem",
        xl: "2rem",
        xxl: "3rem",
        section: "5rem",
      },
      fontFamily: {
        sans: ["var(--qa-font-display)"],
        display: ["var(--qa-font-display)"],
        numeric: ["var(--qa-font-numeric)"],
      },
      fontSize: {
        "display-sm": ["2rem", { lineHeight: "1.2", letterSpacing: "0" }],
        "title-lg": ["1.5rem", { lineHeight: "1.3", letterSpacing: "0" }],
        "title-md": ["1.25rem", { lineHeight: "1.35", letterSpacing: "0" }],
        "title-sm": ["1rem", { lineHeight: "1.4", letterSpacing: "0" }],
        "number-display": ["2.5rem", { lineHeight: "1.1", letterSpacing: "-0.3px" }],
        "number-md": ["1rem", { lineHeight: "1.4", letterSpacing: "0" }],
        "number-sm": ["0.875rem", { lineHeight: "1.4", letterSpacing: "0" }],
        "body-md": ["0.875rem", { lineHeight: "1.5", letterSpacing: "0" }],
        "body-sm": ["0.8125rem", { lineHeight: "1.5", letterSpacing: "0" }],
        caption: ["0.75rem", { lineHeight: "1.4", letterSpacing: "0" }],
      },
    },
  },
} satisfies Config;

export default config;
