from __future__ import annotations

from quantagent.plugin_sdk import BasePlugin, PluginInvokeResult


class PlaceholderSourcePlugin(BasePlugin):
    async def invoke(self, request):
        query = request.input.get("query") or self.context.config.get("query") or "placeholder"
        return PluginInvokeResult(
            output={
                "items": (
                    {
                        "external_id": f"placeholder:{query}",
                        "title": f"Placeholder item for {query}",
                        "content": "Generated by the official placeholder source plugin.",
                        "raw_payload": {"query": query},
                        "metadata": {
                            "plugin_id": self.context.plugin_id,
                            "request_id": request.request_id,
                        },
                    },
                ),
                "next_cursor": None,
                "metadata": {"source": "placeholder"},
            }
        )


plugin = PlaceholderSourcePlugin
